const express = require('express');
const bcrypt = require('bcryptjs');
const { prisma } = require('../db/prisma');
const { validatePassword } = require('../utils/validatePassword');
const { resolveSchoolTerm } = require('../utils/academicTerm');
const { isValidAcademicYear } = require('../utils/academicYear');
const { normalizeSchoolAbbreviation, validateSchoolAbbreviation } = require('../utils/schoolAbbreviation');

const router = express.Router();

router.get('/', async (_req, res) => {
  const schoolId = _req.user.schoolId;
  const school = await prisma.school.findUnique({ where: { id: schoolId } });
  if (!school) {
    return res.status(404).json({ error: 'School settings not found.' });
  }
  res.json(school);
});

// PUT / — updates school settings. Raw academicYear/currentTerm are always
// stored/returned as given (or unchanged) — resolving what to *display* is
// the frontend's job (via the shared academicTerm resolver), computed live
// on every render rather than baked into a response that could get cached.
// If the request touches academicYear or currentTerm without explicitly
// setting autoTermEnabled, that's a manual edit: auto-detect gets switched
// off so the edit sticks instead of being silently overwritten on the next
// read. An explicit autoTermEnabled in the body (the Settings page toggle)
// always wins.
router.put('/', async (req, res) => {
  const schoolId = req.user.schoolId;
  try {
    const current = await prisma.school.findUnique({ where: { id: schoolId } });
    if (!current) {
      return res.status(404).json({ error: 'School settings not found.' });
    }

    const data = { ...req.body };
    const togglesAuto = Object.prototype.hasOwnProperty.call(data, 'autoTermEnabled');
    if (!togglesAuto) {
      // Compare against what the school is CURRENTLY reporting (live-computed
      // when auto is on), not the raw stored row — otherwise re-submitting an
      // untouched, auto-resolved form value would look like a manual edit
      // just because it differs from a stale placeholder in the database.
      const currentDisplay = resolveSchoolTerm(current);
      const editsAcademicYear = Object.prototype.hasOwnProperty.call(data, 'academicYear') && data.academicYear !== currentDisplay.academicYear;
      const editsCurrentTerm = Object.prototype.hasOwnProperty.call(data, 'currentTerm') && data.currentTerm !== currentDisplay.term;
      if (current.autoTermEnabled && (editsAcademicYear || editsCurrentTerm)) {
        data.autoTermEnabled = false;
      }
    }

    // THE ABBREVIATION IS NEVER RE-DERIVED HERE. It is suggested once, from the
    // school name, at signup — and from then on it is whatever the admin has
    // set. This used to recompute it from the name on every save while an
    // auto-generate flag was on, which meant renaming the school silently
    // rewrote an abbreviation the admin may have chosen deliberately.
    //
    // The abbreviationAutoGenerated column is left in place and simply ignored:
    // dropping it would need a migration for no behavioural gain.
    //
    // IT IS NOW VALIDATED RATHER THAN PASSED THROUGH, because it is no longer
    // only a label on the dashboard header — it is the prefix on every receipt
    // number this school issues from here on ("CNPS042"). A prefix containing a
    // space, a slash or a lowercase letter would go onto a paper receipt and
    // into a WhatsApp message, and the parent quoting it back would be quoting
    // something the office search cannot reliably match.
    //
    // Normalised THEN validated: trimming and uppercasing is the one correction
    // that cannot guess wrong, so "cnps" saves as CNPS instead of being bounced
    // back at somebody who meant exactly the right thing. Anything else is
    // refused with the reason.
    //
    // CHANGING IT HERE DOES NOT TOUCH A SINGLE EXISTING RECEIPT, and that is
    // deliberate — a school that switches from CNPS to ENPS gets CNPS001..015
    // followed by ENPS016. Every one of those old numbers is on a receipt in
    // somebody's hands. See the note on School.abbreviation in schema.prisma.
    //
    // Only when PRESENT. Every other save on this page posts its own fields and
    // must not be able to blank the abbreviation by omitting it.
    if (Object.prototype.hasOwnProperty.call(data, 'abbreviation')) {
      const abbreviation = normalizeSchoolAbbreviation(data.abbreviation);
      const invalid = validateSchoolAbbreviation(abbreviation);
      if (invalid) {
        return res.status(400).json({ code: 'INVALID_ABBREVIATION', error: invalid });
      }
      data.abbreviation = abbreviation;
    }

    // The academic year partitions every year-tagged row and is matched by
    // exact string, so a malformed label would file records under a year that
    // does not exist and cannot be selected back. Rejected rather than
    // normalised — guessing what "2026-2027" meant is how data goes missing.
    if (Object.prototype.hasOwnProperty.call(data, 'academicYear') && !isValidAcademicYear(data.academicYear)) {
      return res.status(400).json({
        code: 'INVALID_ACADEMIC_YEAR',
        error: 'Academic year must look like 2026/2027, with consecutive years.',
      });
    }

    // The proprietor's gender is a Postgres enum, so an unrecognised string is
    // rejected by the database itself — as a 500 with a driver message in it,
    // which tells the person at the screen nothing. Checked here so the answer
    // is a 400 that names the problem.
    //
    // NULL AND '' ARE BOTH ALLOWED, and both mean "not set": the field starts
    // unset for every existing school, so clearing it again has to be possible.
    // The empty string is normalised to null rather than passed through, because
    // '' is not a member of the enum and would be refused as invalid — a select
    // reset to its placeholder sends exactly that.
    if (Object.prototype.hasOwnProperty.call(data, 'proprietorGender')) {
      if (data.proprietorGender === '' || data.proprietorGender === null) {
        data.proprietorGender = null;
      } else if (data.proprietorGender !== 'MALE' && data.proprietorGender !== 'FEMALE') {
        return res.status(400).json({
          code: 'INVALID_PROPRIETOR_GENDER',
          error: "Proprietor's gender must be either Male or Female.",
        });
      }
    }

    // THE PUSH NOTIFICATION OPT-OUT, coerced rather than passed through.
    //
    // The body is spread straight into school.update above, so this column would
    // "work" untouched — right up until a client sent the STRING "false", which
    // Prisma refuses outright (a 500 that says nothing useful) or, in the shape
    // this route is most likely to meet it, a checkbox value like "on" that is
    // truthy. A school that switched notifications off and stayed switched on is
    // exactly the failure this toggle exists to prevent, so the value is decided
    // here rather than hoped for.
    //
    // Only when PRESENT. Every other save on this page — the school name, the
    // logo, the academic year — posts its own fields and must not be able to
    // silently re-enable notifications by omitting this one.
    if (Object.prototype.hasOwnProperty.call(data, 'notificationsEnabled')) {
      data.notificationsEnabled = data.notificationsEnabled === true || data.notificationsEnabled === 'true';
    }

    const updated = await prisma.school.update({
      where: { id: schoolId },
      data,
    });
    res.json(updated);
  } catch (e) {
    res.status(500).json({ error: e.message });
  }
});

router.put('/password', async (req, res) => {
  const { currentPassword, newPassword, confirmPassword } = req.body || {};
  if (!currentPassword || !newPassword || !confirmPassword) {
    return res.status(400).json({ code: 'MISSING_FIELDS', error: 'All fields are required.' });
  }
  if (newPassword !== confirmPassword) {
    return res.status(400).json({ code: 'PASSWORD_MISMATCH', error: 'Passwords do not match.' });
  }

  // An account with no hash cannot have a current password to verify, and
  // bcryptjs throws on a null argument rather than returning false — which would
  // surface as a 500. Not reachable as things stand (a session requires a
  // password, and loadAdminActor refuses an account without one being able to
  // log in at all), but this is the one place a null hash would meet bcrypt, so
  // it says no here rather than relying on that staying true.
  if (!req.user.passwordHash) {
    return res.status(400).json({ code: 'WRONG_PASSWORD', error: 'Current password is incorrect.' });
  }
  const currentOk = await bcrypt.compare(String(currentPassword), req.user.passwordHash);
  if (!currentOk) {
    return res.status(400).json({ code: 'WRONG_PASSWORD', error: 'Current password is incorrect.' });
  }

  const pwCheck = validatePassword(String(newPassword));
  if (!pwCheck.valid) {
    return res.status(400).json({ code: 'WEAK_PASSWORD', error: pwCheck.message });
  }

  try {
    const passwordHash = await bcrypt.hash(String(newPassword), 10);
    await prisma.adminUser.update({ where: { id: req.user.id }, data: { passwordHash } });
    res.json({ message: 'Password updated successfully.' });
  } catch (e) {
    res.status(500).json({ error: e.message });
  }
});

module.exports = router;
