-- AlterTable: add both columns nullable first, backfill every existing
-- school's abbreviation from its current name using the same word-initial
-- algorithm applied on every future name change (drop "of"/"and"/"with"/
-- "the"/"&" case-insensitively, take each remaining word's first letter,
-- uppercase), default every existing school to abbreviationAutoGenerated =
-- true (matching what newly created schools get), then enforce NOT NULL.
ALTER TABLE "School" ADD COLUMN "abbreviation" TEXT;
ALTER TABLE "School" ADD COLUMN "abbreviationAutoGenerated" BOOLEAN;

UPDATE "School" s
SET "abbreviation" = (
  SELECT upper(string_agg(left(word, 1), '' ORDER BY ord))
  FROM unnest(regexp_split_to_array(trim(s.name), '\s+')) WITH ORDINALITY AS t(word, ord)
  WHERE word <> '' AND lower(word) NOT IN ('of', 'and', 'with', 'the', '&')
)
WHERE "abbreviation" IS NULL;

UPDATE "School" SET "abbreviationAutoGenerated" = true WHERE "abbreviationAutoGenerated" IS NULL;

ALTER TABLE "School" ALTER COLUMN "abbreviation" SET NOT NULL;
ALTER TABLE "School" ALTER COLUMN "abbreviationAutoGenerated" SET NOT NULL;
ALTER TABLE "School" ALTER COLUMN "abbreviationAutoGenerated" SET DEFAULT true;
